In [ ]:
import random
import math
import numpy as np

In [ ]:
def gcd(a, b):
    """finds the gcd of two numbers"""
    while(b != 0):
        result = b;
        a, b = b, a%b
    return result

In [ ]:
print(gcd(40, 35))

In [ ]:
values = [1,2,3,4,5]
print(random.choice(values)) #select a random value
print(random.sample(values, 2)) #select a set(size=2) of random values
random.shuffle(values) #shuffle the list
print(values)
print(random.randint(0,10)) #get a random value from the given range

In [ ]:
def fib_itr(n):
    if n < 2:
        return n;
    a, b = 0, 1
    for i in range(n):
        a, b = b, a+b
    return a

fib_itr(3)

In [ ]:
def find_prime_sqrt(num):
    if num < 4:
        return True
    for i in range(2,int(math.sqrt(num))+1):
        if num % i == 0:
            return False
    return True

print(find_prime_sqrt(198))

In [ ]:
x = np.array(((random.sample(range(1000), 10)), (random.sample(range(1000), 10)), (random.sample(range(1000), 10))))
print(x)
print(x.ndim)

In [ ]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
print(x)
print(x*2)
print(x+10)
print(np.sqrt(x))
print(np.cos(x))
print(x-y)
print(np.where(x<2, x, y))
m = np.matrix([x,y,x])
print("Matrix:\n",m)
print("m.T:\n", m.T)

In [156]:
grid1 =np.zeros(shape=(10,10), dtype=int)
print(grid1)
grid2 = np.ones(shape=(10,10), dtype=int)
print(grid2)
print(grid1[1]+10)
print(grid2[:,2]*2)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
[10 10 10 10 10 10 10 10 10 10]
[2 2 2 2 2 2 2 2 2 2]
